version: 2
updates:
  - package-ecosystem: docker
    directory: "/http_service"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
  - package-ecosystem: docker
    directory: "/infra"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    allow:
      - dependency-type: direct
      - dependency-type: indirect
  - package-ecosystem: npm
    directory: "/ui/changes"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
  - package-ecosystem: docker
    directory: "/mcp"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
  - package-ecosystem: uv
    directory: "/mcp"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
