repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^tests/fixtures/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        exclude: ^http_service/
        args:
          - --convention=google
          # Ignoring warnings about missing docstrings.
          - --add-ignore=D100,D101,D102,D103,D104,D105,D107
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: trailing-whitespace
        exclude: ^tests/test_repository.py
      - id: check-yaml
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--django"]
      - id: check-json
        exclude: ^tests/fixtures/
      - id: requirements-txt-fixer
      - id: check-vcs-permalinks
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        exclude_types: [json]
  - repo: https://github.com/marco-c/taskcluster_yml_validator
    rev: v0.0.11
    hooks:
      - id: taskcluster_yml
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        name: mypy-bugbug
        files: ^bugbug/|^scripts/|^tests/
        entry: mypy bugbug/ scripts/ tests/
        pass_filenames: false
        additional_dependencies:
          - types-pkg_resources==0.1.2
          - types-python-dateutil==0.1.3
          - types-PyYAML==5.4.0
          - types-orjson==0.1.0
          - types-tabulate==0.9.0.20240106
          - types-requests==0.1.11
      - id: mypy
        name: mypy-bugbug-http
        files: ^http_service/
        entry: mypy http_service/
        pass_filenames: false
        additional_dependencies:
          - types-pkg_resources==0.1.2
          - types-requests==0.1.11
          - types-Flask==1.1.0
          - types-redis==3.5.1
          - types-python-dateutil==0.1.3
          - types-orjson==0.1.0
          - types-tabulate==0.9.0.20240106
  - repo: meta
    hooks:
      - id: check-useless-excludes
default_language_version:
  python: python3.12
