language: python
dist: xenial
python:
  - 3.7
before_install:
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - flake8
  - python run.py --train --goal bug
  - python run.py --goal bug
  - python -m pytest tests/test_*.py
  - python -m bugbug.bug_snapshot
  - python setup.py sdist
  - pip install dist/bugbug-$(cat VERSION).tar.gz
