language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - flake8
  - python run.py --download --train --goal bug
  - python run.py --goal bug
  - python -m pytest tests/test_*.py
  - python setup.py sdist
  - pip install dist/bugbug-$(cat VERSION).tar.gz
