services:
  bugbug-http-service:
    build:
      context: .
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /code/http_service
          initial_sync: true

    image: mozilla/bugbug-http-service
    environment:
      - BUGBUG_BUGZILLA_TOKEN
      - BUGBUG_GITHUB_TOKEN
      - REDIS_URL=redis://redis:6379/0
      - PORT=8000
      - PULSE_USER
      - PULSE_PASSWORD
      - SENTRY_DSN
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - redis

  bugbug-http-service-bg-worker:
    build:
      context: .
      dockerfile: Dockerfile.bg_worker
    image: mozilla/bugbug-http-service-bg-worker
    environment:
      - BUGBUG_BUGZILLA_TOKEN
      - BUGBUG_GITHUB_TOKEN
      - REDIS_URL=redis://redis:6379/0
      - BUGBUG_ALLOW_MISSING_MODELS
      - BUGBUG_REPO_DIR
      - SENTRY_DSN
    depends_on:
      - redis

  bugbug-http-service-rq-dasboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: mozilla/bugbug-http-service-bg-worker
    command:
      - rq-dashboard
      - "-u"
      - "redis://redis:6379/0"
    ports:
      - target: 9181
        published: 9181
        protocol: tcp
        mode: host
    depends_on:
      - redis

  redis:
    image: redis:4
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
